### ISSUE TITLE
Update content in Projects Board

### ISSUE THREAD

**Issue by tomaroberts** [GSTT-CSC/csc-test-site#16]
Issue to track creation of Kanban Board page, i.e.: https://gstt-csc.github.io/work.html

Would suggest calling this "Current Projects" or simply "Projects" instead?

**Comment by tomaroberts** [comment]
Following on from Wed Workshop on 9th March, we decided that each Project will have a designated card similar to the cards used on the Blog page. Suggest you can copy and adapt some of the code Anil created.

**Comment by tomaroberts** [comment]
Made a significant start on this – see PR #47

nb: have merged into `gh-pages` branch already, but Projects Board is still incomplete.

**TODO:**
- [x] Create Project pages layout
- [x] Add in placeholder text for section when zero projects occupy that section. e.g.: "No projects with this status."
- [ ] Add images to all projects
- [ ] Update ALL projects, specifically the `.md` files in `_projects`
- [ ] @lucy-funnell to decide on file-naming/project-naming conventions
- [ ] Finalise text in intro section

**Comment by tomaroberts** [comment]
Closing this – not 100% complete, but plenty enough for MVP.
